import type { Metadata } from 'next'

import Navbar from '@/components/navbar'

import './globals.css'
import { roboto } from '@/fonts'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body className={`${roboto.className} antialiased`}>
        <header>
          <Navbar />
        </header>

        <main className='bg-gradient-to-b from-black to-gray-950'>
          <div className='container mx-auto px-6'>{children}</div>
        </main>
      </body>
    </html>
  )
}
